import type { Lead } from "@/lib/types";

export const leads: Lead[] = [
  {
    id: "lead-1001",
    ownerId: "mgr-asha",
    customerName: "Vikram Sharma",
    phone: "+91 98765 44120",
    email: "vikram.sharma@example.com",
    city: "Indiranagar",
    brandInterested: "Dell",
    laptopModel: "Inspiron 14",
    budget: 68000,
    useCase: "Office",
    preferredSpecs: "i5, 16 GB RAM, 512 GB SSD, lightweight",
    status: "Hot",
    priority: "High",
    salesperson: "Asha Nair",
    leadSource: "WhatsApp",
    nextFollowUpDate: "2026-04-21",
    lastNotePreview: "Wants Dell only, decision after GST quote.",
    createdAt: "2026-04-17",
    updatedAt: "2026-04-21",
    activities: [
      { id: "act-1", type: "Follow-up", title: "Quote sent", body: "Shared Dell Inspiron 14 quote with office warranty details.", createdAt: "2026-04-21 18:10", author: "Asha Nair" },
      { id: "act-2", type: "Call", title: "Needs billing split", body: "Customer asked for GST invoice and EMI options.", createdAt: "2026-04-20 12:35", author: "Asha Nair" }
    ]
  },
  {
    id: "lead-1002",
    ownerId: "mgr-rohan",
    customerName: "Nisha Rao",
    phone: "+91 99880 11224",
    email: "nisha.rao@example.com",
    city: "Koramangala",
    brandInterested: "Lenovo",
    laptopModel: "IdeaPad Slim 5",
    budget: 59000,
    useCase: "Student",
    preferredSpecs: "Ryzen 5, backlit keyboard, good battery",
    status: "Warm",
    priority: "Medium",
    salesperson: "Rohan Mehta",
    leadSource: "Walk-in",
    nextFollowUpDate: "2026-04-23",
    lastNotePreview: "Comparing Lenovo and HP, parent will revisit.",
    createdAt: "2026-04-18",
    updatedAt: "2026-04-21",
    activities: [
      { id: "act-3", type: "Note", title: "Comparison shared", body: "Printed Lenovo vs HP comparison with student discount.", createdAt: "2026-04-21 15:20", author: "Rohan Mehta" }
    ]
  },
  {
    id: "lead-1003",
    ownerId: "mgr-imran",
    customerName: "Arjun Patel",
    phone: "+91 90112 33088",
    city: "Whitefield",
    brandInterested: "Asus",
    laptopModel: "ROG Strix G16",
    budget: 145000,
    useCase: "Gaming",
    preferredSpecs: "RTX 4060, 16 GB RAM, high refresh display",
    status: "Hot",
    priority: "High",
    salesperson: "Imran Khan",
    leadSource: "Instagram",
    nextFollowUpDate: "2026-04-22",
    lastNotePreview: "Needs delivery before Friday, ready for advance.",
    createdAt: "2026-04-19",
    updatedAt: "2026-04-22",
    activities: [
      { id: "act-4", type: "Call", title: "Stock confirmed", body: "Confirmed one unit available. Customer wants card discount.", createdAt: "2026-04-22 10:15", author: "Imran Khan" }
    ]
  },
  {
    id: "lead-1004",
    ownerId: "mgr-neha",
    customerName: "Meera Iyer",
    phone: "+91 77660 11990",
    email: "meera.iyer@example.com",
    city: "Jayanagar",
    brandInterested: "Apple",
    laptopModel: "MacBook Air M3",
    budget: 118000,
    useCase: "Design",
    preferredSpecs: "16 GB unified memory preferred",
    status: "Won",
    priority: "Medium",
    salesperson: "Neha Kapoor",
    leadSource: "Referral",
    nextFollowUpDate: "2026-04-26",
    lastNotePreview: "Closed with extended warranty and sleeve.",
    createdAt: "2026-04-12",
    updatedAt: "2026-04-20",
    activities: [
      { id: "act-5", type: "Status", title: "Marked won", body: "Invoice generated with accessories bundle.", createdAt: "2026-04-20 17:45", author: "Neha Kapoor" }
    ]
  },
  {
    id: "lead-1005",
    ownerId: "mgr-asha",
    customerName: "Sana Qureshi",
    phone: "+91 88994 55440",
    city: "HSR Layout",
    brandInterested: "HP",
    laptopModel: "Pavilion 15",
    budget: 62000,
    useCase: "Business",
    preferredSpecs: "i5, MS Office, onsite support",
    status: "Cold",
    priority: "Low",
    salesperson: "Asha Nair",
    leadSource: "Website",
    nextFollowUpDate: "2026-04-29",
    lastNotePreview: "Asked to call next week after finance approval.",
    createdAt: "2026-04-16",
    updatedAt: "2026-04-19",
    activities: [
      { id: "act-6", type: "Note", title: "Finance pending", body: "No immediate purchase plan. Keep on low touch follow-up.", createdAt: "2026-04-19 11:05", author: "Asha Nair" }
    ]
  },
  {
    id: "lead-1006",
    ownerId: "mgr-rohan",
    customerName: "Karthik Menon",
    phone: "+91 94443 22118",
    email: "karthik.m@example.com",
    city: "Marathahalli",
    brandInterested: "Acer",
    laptopModel: "Swift Go 14",
    budget: 72000,
    useCase: "Programming",
    preferredSpecs: "OLED display, 16 GB RAM, Linux friendly",
    status: "Warm",
    priority: "High",
    salesperson: "Rohan Mehta",
    leadSource: "WhatsApp",
    nextFollowUpDate: "2026-04-20",
    lastNotePreview: "Asked for Linux compatibility confirmation.",
    createdAt: "2026-04-15",
    updatedAt: "2026-04-20",
    activities: [
      { id: "act-7", type: "Follow-up", title: "Compatibility note", body: "Sent model details and suggested dual boot support plan.", createdAt: "2026-04-20 16:40", author: "Rohan Mehta" }
    ]
  },
  {
    id: "lead-1007",
    ownerId: "mgr-imran",
    customerName: "Pranav Kulkarni",
    phone: "+91 90000 78234",
    city: "Malleshwaram",
    brandInterested: "HP",
    laptopModel: "Victus 16",
    budget: 89000,
    useCase: "Gaming",
    preferredSpecs: "RTX 3050 minimum, 1 TB SSD if possible",
    status: "Lost",
    priority: "Low",
    salesperson: "Imran Khan",
    leadSource: "Instagram",
    nextFollowUpDate: "2026-04-18",
    lastNotePreview: "Bought online due to flash discount.",
    createdAt: "2026-04-11",
    updatedAt: "2026-04-18",
    activities: [
      { id: "act-8", type: "Status", title: "Marked lost", body: "Customer selected an online marketplace deal.", createdAt: "2026-04-18 20:10", author: "Imran Khan" }
    ]
  },
  {
    id: "lead-1008",
    ownerId: "mgr-neha",
    customerName: "Devika S",
    phone: "+91 81234 77889",
    email: "devika.s@example.com",
    city: "BTM Layout",
    brandInterested: "Lenovo",
    laptopModel: "Yoga Slim 7",
    budget: 93000,
    useCase: "Design",
    preferredSpecs: "Touch display, color accuracy, 1 kg range",
    status: "Hot",
    priority: "High",
    salesperson: "Neha Kapoor",
    leadSource: "Walk-in",
    nextFollowUpDate: "2026-04-24",
    lastNotePreview: "Will bring old laptop for exchange valuation.",
    createdAt: "2026-04-21",
    updatedAt: "2026-04-22",
    activities: [
      { id: "act-9", type: "Note", title: "Exchange expected", body: "Customer prefers Lenovo Yoga if exchange value crosses 18000.", createdAt: "2026-04-22 13:05", author: "Neha Kapoor" }
    ]
  }
];
